### ISSUE TITLE
希望增加  是否出售  设置

### ISSUE THREAD

**Issue by MilkFoam-L** [CarmJos/UltraDepository#1]
### **功能简述**
能控制玩家是否能出售物品

### **需求来源**
因为服务器有另外经济系统

### **功能参考**(可选)
无

### **附加内容**
无

**Comment by CarmJos** [comment]
是什么意思呀？ 是针对不同玩家而言的可出售权限吗？ 

如果想要关闭物品的出售功能，可以选择将每一件物品的价格(price)或每日售出限制(limit)设置为小于0的数值。也可以选择直接不设定物品的价格和每日售出限制。

如
```yaml
...

items:
 "INK_SAC":
    slot: 11
    price: -1
    limit: -1
    name: "&8&l墨囊"
    lore:
      - " "
      - "&f抓住墨鱼！"

```

也可以直接不设定对应数值。

```yaml
...

items:
 "INK_SAC":
    slot: 11
    name: "&8&l墨囊"
    lore:
      - " "
      - "&f抓住墨鱼！"

```
